"""empty message

Revision ID: 059a7e8cc235
Revises: c12402d9ac7f
Create Date: 2025-09-12 15:45:58.840051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '059a7e8cc235'
down_revision = 'c12402d9ac7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_text', sa.JSON(), nullable=True))
        batch_op.drop_column('placeholders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placeholders', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.drop_column('custom_text')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
