"""empty message

Revision ID: 145db0fe84fd
Revises: d6e806480745
Create Date: 2025-09-19 20:36:49.623923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145db0fe84fd'
down_revision = 'd6e806480745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('layout_data')

    # ### end Alembic commands ###
