"""empty message

Revision ID: 1e4d25d80957
Revises: 2fefe2bbbd27
Create Date: 2025-09-09 13:50:05.882615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e4d25d80957'
down_revision = '2fefe2bbbd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuer_name', sa.String(length=150), nullable=True))

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('body_font_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('layout_style', sa.Enum('classic', 'modern', name='template_layouts'), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('is_public')
        batch_op.drop_column('layout_style')
        batch_op.drop_column('body_font_color')
        batch_op.drop_column('secondary_color')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('issuer_name')

    # ### end Alembic commands ###
