"""empty message

Revision ID: 36ba61278e1d
Revises: dde5908fe6b1
Create Date: 2025-09-15 17:05:30.440958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36ba61278e1d'
down_revision = 'dde5908fe6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=mysql.ENUM('free', 'starter', 'pro', 'credits'),
               type_=sa.Enum('starter', 'growth', 'pro', 'enterprise', name='payment_plans'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.Enum('starter', 'growth', 'pro', 'enterprise', name='payment_plans'),
               type_=mysql.ENUM('free', 'starter', 'pro', 'credits'),
               existing_nullable=False)

    # ### end Alembic commands ###
