"""empty message

Revision ID: 614abcd5f84e
Revises: 829efa0880fe
Create Date: 2025-09-11 03:57:36.740318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614abcd5f84e'
down_revision = '829efa0880fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_expiry')

    # ### end Alembic commands ###
