"""Add cascade delete from templates to certificates

Revision ID: 7878fd9e933a
Revises: 847afd2b9f20
Create Date: 2025-10-09 23:33:30.731197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7878fd9e933a'
down_revision = '847afd2b9f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('certificates_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'templates', ['template_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('certificates_ibfk_2'), 'templates', ['template_id'], ['id'])

    # ### end Alembic commands ###
