"""empty message

Revision ID: 7c23d2059137
Revises: e406772c6ccc
Create Date: 2025-09-13 16:39:21.911162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c23d2059137'
down_revision = 'e406772c6ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_image_url', sa.Text(), nullable=True))
        batch_op.drop_column('signature_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_url', mysql.TEXT(), nullable=True))
        batch_op.drop_column('signature_image_url')

    # ### end Alembic commands ###
