"""empty message

Revision ID: 829efa0880fe
Revises: 1e4d25d80957
Create Date: 2025-09-09 15:48:41.449657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829efa0880fe'
down_revision = '1e4d25d80957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('recipient_email')

    # ### end Alembic commands ###
