"""Update user account deletion

Revision ID: 847afd2b9f20
Revises: 7c0886f2c250
Create Date: 2025-10-09 22:19:16.917323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '847afd2b9f20'
down_revision = '7c0886f2c250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('certificates_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('certificates_ibfk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('payments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('templates_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('templates_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_ibfk_1'), 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('templates_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('templates_ibfk_2'), 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('certificates_ibfk_4'), 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('certificates_ibfk_3'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
