"""empty message

Revision ID: c12402d9ac7f
Revises: 
Create Date: 2025-09-12 00:37:18.767590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12402d9ac7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('free', 'starter', 'pro', name='user_roles'), nullable=False),
    sa.Column('cert_quota', sa.Integer(), nullable=False),
    sa.Column('subscription_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('paystack', 'stripe', 'lemonsqueezy', name='payment_providers'), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', 'credits', name='payment_plans'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payment_statuses'), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('background_url', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('body_font_color', sa.String(length=7), nullable=True),
    sa.Column('font_family', sa.String(length=50), nullable=True),
    sa.Column('layout_style', sa.Enum('classic', 'modern', 'corporate', 'creative', name='template_layouts'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('placeholders', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('course_title', sa.String(length=150), nullable=False),
    sa.Column('issuer_name', sa.String(length=150), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('signature', sa.String(length=150), nullable=True),
    sa.Column('verification_id', sa.String(length=36), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('valid', 'revoked', name='certificate_statuses'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    op.drop_table('templates')
    op.drop_table('payments')
    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###
