"""Add image_url to support messages

Revision ID: d6e806480745
Revises: 94961e8d5a54
Create Date: 2025-09-19 10:29:55.068425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e806480745'
down_revision = '94961e8d5a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
