"""empty message

Revision ID: dde5908fe6b1
Revises: 7c23d2059137
Create Date: 2025-09-13 17:59:58.603621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde5908fe6b1'
down_revision = '7c23d2059137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('extra_fields')

    # ### end Alembic commands ###
