"""empty message

Revision ID: e7eb33e736c4
Revises: e8b0f775fe9d
Create Date: 2025-10-23 23:36:11.048063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7eb33e736c4'
down_revision = 'e8b0f775fe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_expiry')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
