"""Make recipient_email on Certificate optional

Revision ID: e8b0f775fe9d
Revises: 7878fd9e933a
Create Date: 2025-10-16 15:24:13.377873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8b0f775fe9d'
down_revision = '7878fd9e933a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('recipient_email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('recipient_email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
